GUIA6/GUIA6/Models/Medidas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GUIA6.Models
{
    public class Medidas
    {
        public double Variable1 { get; set; }
        public double Variable2 { get; set; }
    }
}

GUIA6/GUIA6/Models/Notas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GUIA6.Models
{
    public class Notas
    {
        public double NOTA1 { get; set; }
        public double NOTA2 { get; set; }
        public double NOTA3 { get; set; }
        public String Mensaje { get; set; }
    }
}

GUIA6/GUIA6/Models/calculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GUIA6.Models
{
    public class calculo
    {
        public int numero1 { get; set; }
        public int numero2 { get; set; }
       
    }
   
}

GUIA6/GUIA6/Controllers/ColegioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GUIA6.Models;
using System.Web.Mvc;

namespace GUIA6.Controllers
{
    public class ColegioController : Controller
    {
        // GET: Colegio
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Notas obNotas)
        {
            string Msj;
            double resultado = (obNotas.NOTA1 + obNotas.NOTA2 + obNotas.NOTA3)/3;
            ViewBag.resultado = resultado;
            if (resultado == 10.00)
            {
                Msj = "Lo Felicito";
                ViewBag.Msj = Msj;
            }
            else if(resultado<10.00 & resultado >= 7.00)
            {
                Msj = "Aprobado ";
                ViewBag.Msj = Msj;
            }
            else if (resultado < 7.00)
            {
                Msj = " necesitas mas Tutorias, recuerda aun puedes seguir adelante";
                ViewBag.Msj = Msj;
            }

            return View(obNotas);


        }
    }
}

GUIA6/GUIA6/Controllers/Ejercicio1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GUIA6.Models;
using System.Web.Mvc;

namespace GUIA6.Controllers
{
    public class Ejercicio1Controller : Controller
    {
        // GET: Ejercicio1
        public ActionResult Index()
        {           
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Medidas obMedidas)
        {

            double resultado1 = obMedidas.Variable1 + obMedidas.Variable2;///De celsius a Kelvin
            ViewBag.resultado1 = resultado1;
            double resultado1_1= obMedidas.Variable1 - obMedidas.Variable2;/// de Kelvin a Celsius
            ViewBag.resultado1_1 = resultado1_1;
            double resultado2 = obMedidas.Variable1 * 2.205; ///De Kilogramos a Libras
            ViewBag.resultado2 = resultado2;
            double resultado2_2 = obMedidas.Variable1 / 2.205;/// De Libras a Kilogramos
            ViewBag.resultado2_2 = resultado2_2;
            double resultado3 = obMedidas.Variable1 * 39.37;/// De metros a Pulgadas
            ViewBag.resultado3 = resultado3;
            return View(obMedidas);
            

        }
    }
}

GUIA6/GUIA6/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GUIA6.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GUIA6/GUIA6/Controllers/PruebaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GUIA6.Models;
using System.Web.Mvc;

namespace GUIA6.Controllers
{
    public class PruebaController : Controller
    {
        // GET: Prueba
        public ActionResult Index()
        {
          

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(calculo obCalculo)
        {
            
            
            int resultado = obCalculo.numero1 + obCalculo.numero2;
            ViewBag.resultado = resultado;
            int resultado2 = obCalculo.numero1 - obCalculo.numero2;
            ViewBag.resultado2 = resultado2;
            double resultado3 = Convert.ToDouble(obCalculo.numero1 / obCalculo.numero2);
            ViewBag.resultado3 = resultado3;
            int resultado4 = obCalculo.numero1 * obCalculo.numero2;
            ViewBag.resultado4 = resultado4;
            return View(obCalculo);
        }
    }
}

GUIA6/GUIA6/Views/Colegio/index.cshtml
@model GUIA6.Models.Notas
@{
    ViewBag.Title = "index";
}
<h2>index</h2>
@using(Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(Model => Model.NOTA1, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.NOTA1, new { @class = "form-control", type = "number" })
    </div>
    <div class="form-group">
        @Html.LabelFor(Model => Model.NOTA2, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.NOTA2, new { @class = "form-control", type = "number" })
    </div>
    <div class="form-group">
        @Html.LabelFor(Model => Model.NOTA3, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.NOTA3, new { @class = "form-control", type = "number" })
    </div>
    <br />
    <div class="form-group">
        <input id="Submit1" type="submit" value="Create" class="btn btn-success" />
    </div>
    <br />
    <br />

    if (ViewBag.resultado != null)
    {

        <p>Resultado de sus notas: &nbsp; @ViewBag.resultado</p>
        <p>Segun su nota:: &nbsp; @ViewBag.Msj</p>
        

    }
}

GUIA6/GUIA6/Views/Ejercicio1/Index.cshtml
@model GUIA6.Models.Medidas

@{
    ViewBag.Title = "Index";
}

<h2>Pesos</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(Model => Model.Variable1, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.Variable1, new { @class = "form-control", type = "number" })
    </div>
    <div class="form-group">
        @Html.LabelFor(Model => Model.Variable2, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.Variable2, new { @class = "form-control", type = "number" })
       
    </div>
    <br />
    <div class="form-group">
        <input id="Submit1" type="submit" value="Create" class="btn btn-success" />
    </div>
    <br />
    <br />

    if (ViewBag.resultado1 != null)
    {
        <p>Resultado de celsius a Kelvin: &nbsp; @ViewBag.resultado1</p>
        <p>Resultado de Kelvin a Celsius: &nbsp; @ViewBag.resultado1_1</p>
        <p>Resultado de Kilgramos a Libras: &nbsp; @ViewBag.resultado2</p>
        <p>Resultado de Libras a Kilogramos: &nbsp; @ViewBag.resultado2_2</p>
        <p>Resultado de Metros a Pulgadas: &nbsp; @ViewBag.resultado3</p>

    }
}

GUIA6/GUIA6/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GUIA6/GUIA6/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GUIA6/GUIA6/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>CARLOS ALBERTO SANCHEZ CASTILLO</h1>
    <p class="lead">Estudiante de programacion dos, amante de la investigacion, mi carnet es 17-0656-2019</p>
    <p><a href="~/Views/Prueba/Index.cshtml" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GUIA6/GUIA6/Views/Prueba/Index.cshtml
@model GUIA6.Models.calculo
@{
    ViewBag.Title = "Index";
}

<h2>Operaciones</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(Model=>Model.numero1, new { @class="control-label" })
        @Html.TextBoxFor(Model => Model.numero1, new {@class="form-control", type="number"})
    </div>
    <div class="form-group">
        @Html.LabelFor(Model => Model.numero2, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.numero2, new { @class = "form-control", type = "number" })
        
    </div>
    <br />
    <div class="form-group">
        <input id="Submit1" type="submit" value="Create" class="btn btn-success" />
    </div>
    <br />
    <br /> 
   
    if (ViewBag.resultado != null)
    {
        <p>Resultado: &nbsp; @ViewBag.resultado</p>
        <p>Resultado de resta: &nbsp; @ViewBag.resultado2</p>
        <p>Resultado de division: &nbsp; @ViewBag.resultado3</p>
        <p>Resultado de Multiplicacion: &nbsp; @ViewBag.resultado4</p>

    }
}

GUIA6/GUIA6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ejercicios de las sumas", "index","Prueba")</li>
                    <li>@Html.ActionLink("Ejercicio del Peso", "Index", "Ejercicio1")</li>
                    <li>@Html.ActionLink("Notas del Colegio", "Index", "Colegio")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>